title: "Andrés Buxó-Lugo"
url: ""
#baseurl:  # comment out if in root directory

comments:
  

style:
  body: 'white'
  margin: 0%
  padding: 30%
  nav: "#222"
  articles: 'stripe' # 'light' 'dark' and 'stripe' possible
  

# see http://fontawesome.io/icons/#brand for all possible icons
# notice: squared icons only work if supported by font-awesome

links:
  - github: {url: "https://github.com/abuxolugo/", square: true}
  - twitter: {url: "https://twitter.com/abuxolugo/", square: true}
  - <i class="ai ai-google-scholar-square ai-3x"></i>: {url: "https://scholar.google.com/citations?user=0BVBMXMAAAAJ&hl=en&oi=ao", square: true}
  - envelope: {url: "mailto:abuxolug@ur.rochester.edu", square: true}


paginate: 1
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines
permalink: pretty
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
plugins: [jekyll-feed, jekyll-paginate] # include feed plugin (supported by gh-pages)
